import javax.swing.*;
import java.awt.event.ActionEvent;

public class AttendeeHomepage {
    private JPanel mainPanel;
    private JLabel welcomeLabel;
    private JButton viewConferencesButton;
    private JButton viewSessionsButton;
    private JButton provideFeedbackButton;
    private JButton logoutButton;

    public AttendeeHomepage(String attendeeName) {
        initComponents();

        // Set welcome label text dynamically
        welcomeLabel.setText("Welcome, " + attendeeName + "!");

        // Add action listeners
        viewConferencesButton.addActionListener(this::viewConferences);
        viewSessionsButton.addActionListener(this::viewSessions);
        provideFeedbackButton.addActionListener(this::provideFeedback);
        logoutButton.addActionListener(this::logout);
    }

    private void viewConferences(ActionEvent e) {
        JOptionPane.showMessageDialog(mainPanel, "View Conferences Clicked");
    }

    private void viewSessions(ActionEvent e) {
        JOptionPane.showMessageDialog(mainPanel, "View Registered Sessions Clicked");
    }

    private void provideFeedback(ActionEvent e) {
        JOptionPane.showMessageDialog(mainPanel, "Provide Feedback Clicked");
    }

    private void logout(ActionEvent e) {
        JOptionPane.showMessageDialog(mainPanel, "Logout Clicked");
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    private void initComponents() {
        // DO NOT MODIFY: Generated by JFormDesigner
        mainPanel = new JPanel();
        welcomeLabel = new JLabel();
        viewConferencesButton = new JButton();
        viewSessionsButton = new JButton();
        provideFeedbackButton = new JButton();
        logoutButton = new JButton();

        // Main Panel Layout
        mainPanel.setLayout(new BoxLayout(mainPanel, BoxLayout.Y_AXIS));

        // Welcome Label
        welcomeLabel.setText("Welcome, Attendee!");
        welcomeLabel.setHorizontalAlignment(SwingConstants.CENTER);
        mainPanel.add(welcomeLabel);

        // Buttons
        viewConferencesButton.setText("View Conferences");
        mainPanel.add(viewConferencesButton);

        viewSessionsButton.setText("View Registered Sessions");
        mainPanel.add(viewSessionsButton);

        provideFeedbackButton.setText("Provide Feedback");
        mainPanel.add(provideFeedbackButton);

        logoutButton.setText("Logout");
        mainPanel.add(logoutButton);
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("Attendee Homepage");
        AttendeeHomepage homepage = new AttendeeHomepage("John Doe");
        frame.setContentPane(homepage.getMainPanel());
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }
}
